### ISSUE TITLE
add temp_call_number

### ISSUE THREAD

**Issue by kathrin77** [HSG-Library/print-slip-report#13]
would it be possible to add the temp_call_number to the print slip? One of our libraries uses the temporary call number field and would like to print it on the slip.

**Comment by d22** [comment]
Hi @kathrin77 

This is definitely possible, I just released a beta version (v2023.11.1-beta). Can you please check if ne new column works as desired? 
(In case you never tested a beta CloudApp: To activate the beta, click the blue "i" on the CloudApp in Alma and then the "(Try: v2023.11.1-beta)" link in the description.) 
If it works, I will release the beta into production.

br
Jonas

**Comment by kathrin77** [comment]
Hi @d22 thanks for the quick reply! It seems perfect from my pov, but I would like to have it confirmed by the library who actually works with those temporary call numbers, I am waiting for feedback and will let you know. br, Kathrin

**Comment by d22** [comment]
Hi @kathrin77 
I just released a new version with the new column in (see PR #14).
Br, Jonas

(for internal reference/documentation, @kathrin77's SLSP ticket regarding the library-mix-up issue: [SLSP-SUPPORT-28221](https://slsp.atlassian.net/servicedesk/customer/portal/1/SUPPORT-28221))
